### ISSUE TITLE
upgrading the framework on running cluster. 

### ISSUE THREAD

**Issue by samek** [mesosphere/cassandra-mesos-deprecated#137]
Hi, 

We're currently running 0.1.1-SNAPSHOT-514-master-a6a94fbb.  (through marathon)

How should we approach upgrade to 0.2.1 ? Just update the app in marathon ?  
I would like to have things running like they are right now...

**Comment by samek** [comment]
Anyone ?

**Comment by elingg** [comment]
Hi @samek, is your goal to simply upgrade the framework scheduler? If yes, it seems that should be possible by updating the app in Marathon. @BenWhitehead can jump in and let us know any additional details.

**Comment by samek** [comment]
@elingg Yes, just the scheduler.

**Comment by kensipe** [comment]
@samek Is there anything else to follow up on here?

**Comment by samek** [comment]
@kensipe I've tried upgrading just the tar and marathon json and it did upgrade.

**Comment by keithchambers** [comment]
@samek as you discovered, we don't have a story around upgrade at the moment.

Backup and restore was added recently: https://github.com/mesosphere/cassandra-mesos/blob/master/docs/docs/backup-and-restore.md

While admittedly very crude, you should be able to use backup and restore as a method of upgrade once you get the a version of the scheduler that supports it.

**Comment by BenWhitehead** [comment]
Correct, the version of cassandra didn't change between 0.1.1-SNAPSHOT and 0.2.1-SNAPSHOT, there were some changes to the persisted configuration for the cluster and nodes, but the code should handled updating correctly since it's protobuf.

Things will get much more complicated when the version of cassandra itself is changing.

**Comment by triclambert** [comment]
This repository is deprecated. Please use the latest supported framework here: https://github.com/mesosphere/dcos-cassandra-service, and provide feedback for us here:  https://dcosjira.atlassian.net/browse/CASSANDRA.
