### ISSUE TITLE
Cassandra ignores set-up parameters

### ISSUE THREAD

**Issue by AndriiOmelianenko** [mesosphere/cassandra-mesos-deprecated#140]
Hi guys,

Cassandra DCOS package ignores all configuration parameters and doesn't allow to change settings.

Any options regarding data directory, RAM, CPU and so on are ignored, there is no way to customize DCOS Cassandra package installation atm.

**Comment by kensipe** [comment]
@AndriiOmelianenko 

I submitted a PR to the universe to make resources configurable:  https://github.com/mesosphere/universe/pull/231

would love a PR for anything else you are looking for..

**Comment by triclambert** [comment]
This repository is deprecated. Please use the latest supported framework here: https://github.com/mesosphere/dcos-cassandra-service, and provide feedback for us here: https://dcosjira.atlassian.net/browse/CASSANDRA.
