### ISSUE TITLE
Support configurable logging level

### ISSUE THREAD

**Issue by keithchambers** [mesosphere/cassandra-mesos-deprecated#147]
Add support for runtime (re)configuring Cassandra log level to enable operators to troubleshoot Cassandra.  i.e., reconfigure the log level from INFO to DEBUG

Because logging can impact Cassandra performance, as part of this feature we need to consider if the logging level will be a global setting (all nodes) or a per node setting.

More details on Cassandra logging and configuration are available here: http://docs.datastax.com/en/cassandra/2.0/cassandra/configuration/configLoggingLevels_t.html

**Comment by triclambert** [comment]
This repository is deprecated. Please use the latest supported framework here: https://github.com/mesosphere/dcos-cassandra-service, and provide feedback for us here:  https://dcosjira.atlassian.net/browse/CASSANDRA.
