### ISSUE TITLE
I can't find the Datastax java driver extension.

### ISSUE THREAD

**Issue by ajazam** [mesosphere/cassandra-mesos-deprecated#148]
Hello,

Didn't know where a questions so I created this.

I can't find the code for the datastax java driver extension. Can somebody help?

I want to have a play with cassandra-mesos.

**Comment by elingg** [comment]
We currently don't support the Datastax Enterprise Version and support only the Open Source Cassandra at this time. Please let us know if that answers your question.

**Comment by ajazam** [comment]
I don't have the Datastax enterprise version, I'm using the open source version at home. I wouldn't work out where the driver extensions were to allow the cassandra java driver to talk to zookeeper to get the IP of a seed node. Or am I missing something?

**Comment by elingg** [comment]
Is your final goal to find the IP address of a seed node? Just trying to understand.

**Comment by ajazam** [comment]
Yes. I want an IP for the seed node(s), so I can contact the cassandra cluster. If you're not ready then I'll hack something that works, somehow. I'm new to mesos so I'm having fun as I'm learning :)

**Comment by triclambert** [comment]
This repository is deprecated. Please use the latest supported framework here: https://github.com/mesosphere/dcos-cassandra-service, and provide feedback for us here:  https://dcosjira.atlassian.net/browse/CASSANDRA.
