### ISSUE TITLE
Node instance is failing to come up after the reboot and scheduler restart

### ISSUE THREAD

**Issue by dlyub** [mesosphere/cassandra-mesos-deprecated#154]
Here's the scenario that's not working for me:
1. scaled the number of scheduler instances to 0 in Marathon
2. scaled the number of scheduler instances to 1 in Marathon. Scheduler is now running on different mesos slave/port.
3. restarted cassandra node host. Node is failing to start because it's trying to pull java from the location where the original scheduler used to reside. 

Has anyone else seen this behavior? Are there any ways to fix this?

Thank you!

**Comment by BenWhitehead** [comment]
Hi @dlyub, this is a bug that was fixed in version 0.2.0 and should no longer be happening. If you're running 0.1.0 please upgrade (it can be performed in place and shouldn't require anything extra from you beside using the new artifacts).  After upgrading you'll need to issue a restart for that node to the rest api by sending `POST /node/{node}/restart` and the framework should restart that node.

**Comment by dlyub** [comment]
@BenWhitehead we're currently on 0.2.0-1. Is there something in the config / env / logs I should be checking?

**Comment by BenWhitehead** [comment]
Try grepping for `TASK_ERROR` in `cassandra-mesos.log`, this should output the error response from mesos if the task is invalid (telling to to run the task in an executor that doesn't exist [the bug that was fixed in 0.2.0]).

If that doesn't turn up anything, grepping for `TASK_FALIURE` should provide more info about which task is failing and the data that's going into it.

**Comment by dlyub** [comment]
here's what I see in stderr and cassandra-mesos.log

I1109 20:32:04.112392 14339 fetcher.cpp:414] Fetcher Info: {"cache_directory":"\/tmp\/mesos\/fetch\/slaves\/e3975add-1363-4231-8e59-d03c9351fdac-S5\/root","items":[{"action":"BYPASS_CACHE","uri":{"extract":true,"value":"http:\/\/my_slave_node:31652\/jre-7-linux.tar.gz"}},{"action":"BYPASS_CACHE","uri":{"extract":true,"value":"http:\/\/my_slave_node:31652\/apache-cassandra-2.1.4-bin.tar.gz"}},{"action":"BYPASS_CACHE","uri":{"extract":false,"value":"http:\/\/my_slave_node:31652\/cassandra-executor.jar"}}],"sandbox_directory":"\/tmp\/mesos\/slaves\/e3975add-1363-4231-8e59-d03c9351fdac-S5\/frameworks\/e3975add-1363-4231-8e59-d03c9351fdac-0001\/executors\/cassandra.dev-test.node.1.executor\/runs\/f3b3e694-70f8-4114-a95a-8ea16a818154","user":"root"}
I1109 20:32:04.113723 14339 fetcher.cpp:369] Fetching URI 'http://my_slave_node:31652/jre-7-linux.tar.gz'
I1109 20:32:04.113736 14339 fetcher.cpp:243] Fetching directly into the sandbox directory
I1109 20:32:04.113746 14339 fetcher.cpp:180] Fetching URI 'http://my_slave_node:31652/jre-7-linux.tar.gz'
I1109 20:32:04.113755 14339 fetcher.cpp:127] Downloading resource from 'http://my_slave_node:31652/jre-7-linux.tar.gz' to '/tmp/mesos/slaves/e3975add-1363-4231-8e59-d03c9351fdac-S5/frameworks/e3975add-1363-4231-8e59-d03c9351fdac-0001/executors/cassandra.dev-test.node.1.executor/runs/f3b3e694-70f8-4114-a95a-8ea16a818154/jre-7-linux.tar.gz'
Failed to fetch 'http://my_slave_node:31652/jre-7-linux.tar.gz': Error downloading resource: Couldn't connect to server
Failed to synchronize with slave (it's probably exited)



2015-11-09 20:07:18,212 DEBUG [Thread-75] i.m.m.f.c.s.CassandraScheduler - {taskId:cassandra.dev-test.node.1.executor} > statusUpdate(driver : org.apache.mesos.MesosSchedulerDriver@1c2d0ca6, status : task_id { value: "cassandra.dev-test.node.1.executor" } state: TASK_FAILED message: "" slave_id { value: "e3975add-1363-4231-8e59-d03c9351fdac-S5" } timestamp: 1.447099638065617E9 executor_id { value: "cassandra.dev-test.node.1.executor" } source: SOURCE_SLAVE reason: REASON_MEMORY_LIMIT uuid: "\3669\353\024\027\335J\373\252`1\036\356\244K`" 13: "\n\016\022\f10.240.7.236")
2015-11-09 20:07:18,212 ERROR [Thread-75] i.m.m.f.c.s.CassandraScheduler - {taskId:cassandra.dev-test.node.1.executor} Got status TASK_FAILED for task cassandra.dev-test.node.1.executor, executor cassandra.dev-test.node.1.executor (REASON_MEMORY_LIMIT, healthy=false): 
2015-11-09 20:07:18,223 TRACE [Thread-75] i.m.m.f.c.s.CassandraScheduler - {taskId:cassandra.dev-test.node.1.executor} < statusUpdate(driver : org.apache.mesos.MesosSchedulerDriver@1c2d0ca6, status : task_id { value: "cassandra.dev-test.node.1.executor" } state: TASK_FAILED message: "" slave_id { value: "e3975add-1363-4231-8e59-d03c9351fdac-S5" } timestamp: 1.447099638065617E9 executor_id { value: "cassandra.dev-test.node.1.executor" } source: SOURCE_SLAVE reason: REASON_MEMORY_LIMIT uuid: "\3669\353\024\027\335J\373\252`1\036\356\244K`" 13: "\n\016\022\f10.240.7.236")

**Comment by BenWhitehead** [comment]
It sounds like the scheduler didn't properly detect that the executor was lost.

If you have another node available in your cluster that could run cassandra the easiest thing to do to sidestep this issue would be to `TERMINATE` it with `POST /node/{node}/terminate` and the framework should replace it when the next resources offer comes in.

**Comment by juicedM3** [comment]
We've seen this same issue but through a different scenario. We're running cassandra-mesos 0.2.1. We started the framework and discovered the next day it fell over. The most likely scenario we could come up with was the the scheduler moved hosts and then 2 of the mesos-agent where nodes were running restarted. The nodes were still pointing to the first server the scheduler was running on and couldn't download the archives. We reproduced this by killing the scheduler, letting it respawn on a different host and then restart the mesos-agent where one of the nodes were running.

Our setup that the following logs are based off of:

scheduler: ms136
nodes: ms43, ms54, ms137

Digging through our logs, this is what we saw:

stderr
```
I1201 01:40:17.713582 24837 exec.cpp:452] Slave exited, but framework has checkpointing enabled. Waiting 15mins to reconnect with slave 20151029-080001-4053860618-5050-23715-S151
I1201 01:40:52.298522 24911 sched.cpp:819] Got error 'Framework failed over'
I1201 01:40:52.298596 24911 sched.cpp:1625] Asked to abort the driver
I1201 01:40:52.299443 24911 sched.cpp:861] Aborting framework '20151119-161726-4053860618-5050-2797-0051'
I1201 01:40:52.317241 24871 sched.cpp:1591] Asked to stop the driver
I1201 01:40:52.317375 24932 sched.cpp:835] Stopping framework '20151119-161726-4053860618-5050-2797-0051’
```

cassandra-mesos.log
```
2015-12-01 01:40:37,383 ERROR [Thread-20064] i.m.m.f.c.s.CassandraScheduler - {taskId:cassandra.cassandra-chronos.node.2.executor.server} Got status TASK_LOST for task cassandra.cassandra-chronos.node.2.executor.server, executor  (REASON_SLAVE_REMOVED, healthy=false): Slave ms54.example.com removed: a new slave registered at the same address
2015-12-01 01:40:37,514 ERROR [Thread-20065] i.m.m.f.c.s.CassandraScheduler - {taskId:cassandra.cassandra-chronos.node.2.executor} Got status TASK_LOST for task cassandra.cassandra-chronos.node.2.executor, executor (REASON_SLAVE_REMOVED, healthy=false): Slave ms54.example.com removed: a new slave registered at the same address
2015-12-01 01:40:37,937 ERROR [Thread-20109] i.m.m.f.c.s.CassandraScheduler - {taskId:cassandra.cassandra-chronos.node.0.executor.server} Got status TASK_LOST for task cassandra.cassandra-chronos.node.0.executor.server, executor  (REASON_SLAVE_REMOVED, healthy=false): Slave ms137.example.com removed: a new slave registered at the same address
2015-12-01 01:40:38,205 ERROR [Thread-20110] i.m.m.f.c.s.CassandraScheduler - {taskId:cassandra.cassandra-chronos.node.0.executor} Got status TASK_LOST for task cassandra.cassandra-chronos.node.0.executor, executor (REASON_SLAVE_REMOVED, healthy=false): Slave ms137.example.com removed: a new slave registered at the same address
2015-12-01 01:40:52,298 ERROR [Thread-20174] i.m.m.f.c.s.CassandraScheduler - {} error(driver : org.apache.mesos.MesosSchedulerDriver@69a8bf4f, message : Framework failed over)2015-12-01 01:40:52,315 INFO  [main] o.g.g.http.server.NetworkListener - {} Stopped listener bound to [ms136.example.com:31538]
```
As the nodes tried to re-spawn, we saw this in the process table:

```
root     19533  4176  0 21:42 ?        00:00:00 mesos-containerizer launch --command={"environment":{"variables":[{"name":"JAVA_OPTS","value":"-Xms256m -Xmx256m"},{"name":"MESOSPHERE_LD_LIBRARY_PATH","value":"\/opt\/mesosphere\/lib"}]},"shell":true,"uris":[{"extract":true,"value":"http:\/\/ms136.example.com:31538\/jre-7-linux.tar.gz"},{"extract":true,"value":"http:\/\/ms136.example.com:31538\/apache-cassandra-2.1.4-bin.tar.gz"},{"extract":false,"value":"http:\/\/ms136.example.com:31538\/cassandra-executor.jar"}],"value":"export LD_LIBRARY_PATH=$MESOSPHERE_LD_LIBRARY_PATH:$LD_LIBRARY_PATH &&  $(pwd)\/jre*\/bin\/java -XX:+PrintCommandLineFlags $JAVA_OPTS -classpath cassandra-executor.jar io.mesosphere.mesos.frameworks.cassandra.executor.CassandraExecutor"} --commands={"commands":[]} --directory=/tmp/mesos/slaves/20151125-224940-648086282-5050-28250-S1/frameworks/20151125-224940-648086282-5050-28250-0006/executors/cassandra.dev-test.node.2.executor/runs/c2d46c4b-466a-426a-a49f-7f42168f7514 --help=false --pipe_read=13 --pipe_write=19 --user=root
```

But by now the scheduler is running on ms102 port 31729. I was also able to decode the ZK data and saw the following info even after the scheduler moved:

```
Cassandra Node Host ms43.example.com 
        File Download URI http://ms136.example.com:31538/jre-7-linux.tar.gz  
        File Download URI http://ms136.example.com:31538/apache-cassandra-2.1.4-bin.tar.gz 
        File Download URI http://ms136.example.com:31538/cassandra-executor.jar
 
Cassandra Node Host ms54.example.com
        File Download URI http://ms136.example.com:31538/jre-7-linux.tar.gz
        File Download URI http://ms136.example.com:31538/apache-cassandra-2.1.4-bin.tar.gz
        File Download URI http://ms136.example.com:31538/cassandra-executor.jar
        
Cassandra Node Host ms137.example.com
        File Download URI http://ms136.example.com:31538/jre-7-linux.tar.gz
        File Download URI http://ms136.example.com:31538/apache-cassandra-2.1.4-bin.tar.gz
        File Download URI http://ms136.example.com:31538/cassandra-executor.jar
```
I'm not sure if the ZK data is used to re-launch any node after the agent was lost (mesos-containerizer launch). I'm still trying to wrap my head around the source code. But it seems like a logical place for it to look for information to launch itself. The only issue is that it's outdated.

**Comment by abrashid** [comment]
Hi  juicedM3,

I am having also the similar issue:

I0310 11:07:34.817458 31808 sched.cpp:264] No credentials provided. Attempting to register without authentication
E0310 11:09:42.033685 31815 socket.hpp:107] Shutdown failed on fd=37: Transport endpoint is not connected [107]
I0310 11:10:12.377645 31814 sched.cpp:819] Got error 'Completed framework attempted to re-register'
I0310 11:10:12.377678 31814 sched.cpp:1625] Asked to abort the driver
I0310 11:10:12.378490 31814 sched.cpp:861] Aborting framework '20160309-183453-2497969674-5050-19271-0001'
I0310 11:10:12.386880 31794 sched.cpp:1591] Asked to stop the driver
I0310 11:10:12.387462 31809 sched.cpp:835] Stopping framework '20160309-183453-2497969674-5050-19271-0001'

Any solution for this?

Best regards,
Abu

**Comment by juicedM3** [comment]
Abu,

My workaround was to modify the source code. I moved the archives to a known server so that they never move. I then added the option to specify a DOWNLOAD_HOST.

```
$ git diff cassandra-mesos-framework/src/main/java/io/mesosphere/mesos/frameworks/cassandra/framework/Main.java
diff --git a/cassandra-mesos-framework/src/main/java/io/mesosphere/mesos/frameworks/cassandra/framework/Main.java b/cassandra-mesos-framework/src/main/java/io
index 299e70a..343951c 100644
--- a/cassandra-mesos-framework/src/main/java/io/mesosphere/mesos/frameworks/cassandra/framework/Main.java
+++ b/cassandra-mesos-framework/src/main/java/io/mesosphere/mesos/frameworks/cassandra/framework/Main.java
@@ -124,6 +124,7 @@ public final class Main {
 
         final int port0 = Integer.parseInt(portOption.get());
         final String host = Env.option("HOST").or("localhost");
+        final String downloadHost = Env.option("DOWNLOAD_HOST").or(Env.option("HOST")).or("localhost");
 
         final Optional<String> clusterNameOpt = Env.option("CASSANDRA_CLUSTER_NAME");
 
@@ -201,7 +202,8 @@ public final class Main {
             frameworkBuilder.setId(frameworkId(frameworkId.get()));
         }
 
-        final URI httpServerBaseUri = URI.create("http://" + host + ":" + port0 + "/");
+        final URI httpServerBaseUri = URI.create("http://" + downloadHost + ":" + port0 + "/");
+        final URI httpServerBase = URI.create("http://" + host + ":" + port0 + "/");
 
         final Clock clock = new SystemClock();
         final PersistedCassandraClusterHealthCheckHistory healthCheckHistory = new PersistedCassandraClusterHealthCheckHistory(state);
@@ -254,7 +256,7 @@ public final class Main {
                 new ScaleOutController(cassandraCluster, factory),
                 provider
             );
-        final HttpServer httpServer = GrizzlyHttpServerFactory.createHttpServer(httpServerBaseUri, rc);
+        final HttpServer httpServer = GrizzlyHttpServerFactory.createHttpServer(httpServerBase, rc);
 
         final MesosSchedulerDriver driver;
         final Optional<Credential> credentials = getCredential();
```

Another option without modifying the source code would be to setup mesos-dns or consul + mesos-consul. Then you could set HOST to something like:

```
cassandra-mesos.service.consul
```
And when cassandra-mesos moves to a new host, mesos-consul will update the record in consul and cassandra-mesos should be able to find the archives it needs to run.

**Comment by dlyub** [comment]
just 'fixed' this problem by doing 'rmr /cassandra-mesos' in zkCli and restarting the scheduler

**Comment by triclambert** [comment]
This repository is deprecated. Please use the latest supported framework here: https://github.com/mesosphere/dcos-cassandra-service, and provide feedback for us here: https://dcosjira.atlassian.net/browse/CASSANDRA.
