### ISSUE TITLE
Support for Cassandra 2.2.x

### ISSUE THREAD

**Issue by juicedM3** [mesosphere/cassandra-mesos-deprecated#155]
Is there any plan to support Cassandra 2.2.x?

**Comment by jdoklovic** [comment]
++ for Cassandra 2.2.x

**Comment by mcoffin** [comment]
I have a [branch](https://github.com/mcoffin/cassandra-mesos/tree/cassandra-3.1%231) that works (at least minimal features tested... working on more extensive testing now) for Cassandra `3.1`. The edits I made there should make it *very* easy to configure to use cassandra 2.2 though.

Keep in mind that any time you're switching versions around, a lot of unforeseen things may start breaking out of the blue.

**Comment by jdoklovic** [comment]
Awesome @mcoffin I'll give it a go.
Quick question... There's talk of Cassandra.yaml in the readme but I can't figure out how to provide a custom file to override the defaults. Any ideas?

**Comment by elisehuard** [comment]
++ there's been quite a few changes since 2.1.4

**Comment by triclambert** [comment]
This repository is deprecated. Please use the latest supported framework here: https://github.com/mesosphere/dcos-cassandra-service.  We currently support the 3.0.x line of releases.
