### ISSUE TITLE
Cassandra-Mesos and SSL?

### ISSUE THREAD

**Issue by achalupa74** [mesosphere/cassandra-mesos-deprecated#159]
Is it possible to use cassandra-mesos in such a way that Cassandra is exposed securely?  Since Cassandra is a database our implementation will require that we use SSL between clients and cassandra as well as the inter node communication.

Any tips on how to make Cassandra secure when using the cassandra-mesos plugin?

If it's not supported yet do you have a projection as to when it might be supported?

Thanks!

**Comment by triclambert** [comment]
This repository is deprecated.  Please use the latest supported framework here:  https://github.com/mesosphere/dcos-cassandra-service.  However, we do not yet support SSL.  Please file a feature request if you're still interested in this:  https://dcosjira.atlassian.net/browse/CASSANDRA
