### ISSUE TITLE
Tutorial of using vagrant and/or virtualbox to setup dev cluster

### ISSUE THREAD

**Issue by zhitaoli** [mesosphere/cassandra-mesos-deprecated#160]
It seems like more and more Mesos frameworks start to provide an initial Vagrant file for setting a local dev instance in a VM (with virtualbox as first choice). It's a pretty convenient way for newbies to get a local dev environment set up and familiarize with the framework.

An example from myriad: https://github.com/apache/incubator-myriad/blob/master/docs/vagrant.md

Has this been ever brought up with cassandra-mesos? If you think could be useful for the community, I can try to pursue this a little bit?

Thanks!

**Comment by triclambert** [comment]
This repository is deprecated. Please use the latest supported framework here: https://github.com/mesosphere/dcos-cassandra-service.
