### ISSUE TITLE
Scheduler fails trying to increase the number of nodes

### ISSUE THREAD

**Issue by dmitriybondr** [mesosphere/cassandra-mesos-deprecated#162]
After sending this request to a scheduler it sometimes fails, but sometimes count of nodes are increased, but scheduler is restarted on another node.
Is it a necessary behavior to restart scheduler after increasing number of nodes using API?
{
        "contentType": [
            "application/json"
        ],
        "method": "POST",
        "url": "http://localhost:18080/scale/nodes?nodeCount={count}"
    },

**Comment by triclambert** [comment]
This repository is deprecated.  Please use the latest supported framework here:  https://github.com/mesosphere/dcos-cassandra-service.
