### ISSUE TITLE
Adjust resources(memory, cpu etc) allocated to each cassandra node after cassandra-mesos gets deployed.

### ISSUE THREAD

**Issue by allenxiang** [mesosphere/cassandra-mesos-deprecated#163]
It seems right now there is no way to adjust resources(memory, cpu etc) allocated to each cassandra node after cassandra-mesos gets deployed. Currently I have to tear down the whole cassandra-mesos framework and redeploy it in order to increase memory for each cassandra node. In this case, all the cassandra data will be gone.

A good example to follow will be the kafka-mesos framework. https://github.com/mesos/kafka#updating-broker-configurations.
Its rest api allow us to stop a node, update configuration (including memory/cpu etc.) and restart it.

**Comment by triclambert** [comment]
This repository is deprecated.  Please use the latest supported framework here:  https://github.com/mesosphere/dcos-cassandra-service.
