### ISSUE TITLE
Trouble with starting Cassandra cluster 

### ISSUE THREAD

**Issue by rvesselinov** [mesosphere/cassandra-mesos-deprecated#165]
Hello, 

I try to start Cassandra Mesos (0.2.0-1) on Messos framework(0.26.0)  with Marathon (0.13.0) but there is problem with retrieval of the executor metadata and the scheduler declines the offers constantly:
https://gist.github.com/rvesselinov/31a2bae2e52f7d940682
Same happens also with cassandra-mesos 0.2.1-SNAPSHOT-608-master.

The Marathon task for Cassandra is with following configuration:
https://gist.github.com/rvesselinov/8c44ede4727652ed1041

These are cassandra-mesos logs:
[cassandra-mesos.log.zip](https://github.com/mesosphere/cassandra-mesos/files/118914/cassandra-mesos.log.zip)
And system output:
[stdout.txt](https://github.com/mesosphere/cassandra-mesos/files/118920/stdout.txt)
[stderr.txt](https://github.com/mesosphere/cassandra-mesos/files/118919/stderr.txt)

And this is the slaves state on which Mesos is running:
[state.zip](https://github.com/mesosphere/cassandra-mesos/files/118916/state.zip)

Regards, Rado

**Comment by triclambert** [comment]
This repository is deprecated.  Please use the latest supported framework here:  https://github.com/mesosphere/dcos-cassandra-service.
