### ISSUE TITLE
Allow cassandra scheduler to inject a java agent into cassandra jvm.

### ISSUE THREAD

**Issue by allenxiang** [mesosphere/cassandra-mesos-deprecated#166]
We need a way for cassandra scheduler to inject a java agent(e.g. jmx exporter) into cassandra jvm so that we can instrument cassandra better.

**Comment by triclambert** [comment]
This repository is deprecated.  Please use the latest supported framework here:  https://github.com/mesosphere/dcos-cassandra-service.  It supports proper JMX configuration.

**Comment by triclambert** [comment]
This repository is deprecated.  Please use the latest supported framework here:  https://github.com/mesosphere/dcos-cassandra-service.  It supports proper JMX configuration.
