### ISSUE TITLE
Unresolveable build extension: maven-protoc-plugin:0.4.0

### ISSUE THREAD

**Issue by ray-** [mesosphere/cassandra-mesos-deprecated#168]
The `pom.xml` is referring to a URL that doesn't exist: http://sergei-ivanov.github.com/maven-protoc-plugin/repo/releases

I'll try to hunt around for it.

Full error here:

> The project io.mesosphere.mesos.frameworks.cassandra:cassandra-mesos-model:0.2.1-SNAPSHOT (/home/vagrant/cassandra-on-mesos/cassandra-mesos/cassandra-mesos-model/pom.xml) has 1 error
> [ERROR]     Unresolveable build extension: Plugin com.google.protobuf.tools:maven-protoc-plugin:0.4.0 or one of its dependencies could not be resolved: Failure to find com.google.protobuf.tools:maven-protoc-plugin:jar:0.4.0 in http://sergei-ivanov.github.com/maven-protoc-plugin/repo/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of protoc-plugin has elapsed or updates are forced -> [Help 2]

**Comment by rahulkumar-aws** [comment]
+1

**Comment by triclambert** [comment]
This repository is deprecated.  Please use the latest supported framework here:  https://github.com/mesosphere/dcos-cassandra-service.
