### ISSUE TITLE
Adding Nodes to a cluster

### ISSUE THREAD

**Issue by eastlondoner** [mesosphere/cassandra-mesos-deprecated#169]
I've got cassandra-mesos running as a dcos package and it's working great with 3 nodes. 
I want to add cassandra nodes but I cannot work out how to do it from the docs.

I've tried running:
dcos cassandra node cluster resize --json cassandra.dcos 5

which completes without any output but my cluster size and number of cassandra tasks remains the same.

**Comment by eastlondoner** [comment]
it turns out I only had 4 nodes in my cluster - works fine going from 3 -> 4.
It probably would be better if it didn't fail silently though

**Comment by triclambert** [comment]
This repository is deprecated.  Please use the latest supported framework here:  https://github.com/mesosphere/dcos-cassandra-service.
