### ISSUE TITLE
Use persistent volumes for data storage

### ISSUE THREAD

**Issue by eastlondoner** [mesosphere/cassandra-mesos-deprecated#170]
It seems like persistent volumes would be great for cassandra (It is even mentioned by name in the docs on mesos!):
http://mesos.apache.org/documentation/latest/persistent-volume/
Is there a plan to add support for persistent volumes? 
What is required to make it work?

**Comment by triclambert** [comment]
This repository is deprecated.  Please use the latest supported framework here:  https://github.com/mesosphere/dcos-cassandra-service.  It fully supports persistent volumes from Mesos.
