### ISSUE TITLE
Support for production Workload DC OS and DataStax Cassandra latest Versions

### ISSUE THREAD

**Issue by matses72** [mesosphere/cassandra-mesos-deprecated#173]
Hi, looking for a **Support Statement** running **DataStax Cassandra on DC OS Enterprise** - the only thing i found was on Docs: https://mesosphere.github.io/cassandra-mesos/docs/
that there is no support for production workload - not sure if this is also true for running on dcos inside a Docker Container or if it is only true for mesos container format.

**Comment by triclambert** [comment]
This project is deprecated.  It will be archived on December 1, 2017.  Instead, please check out [Apache Cassandra for DC/OS](https://docs.mesosphere.com/service-docs/cassandra/) or [DataStax Enterprise for DC/OS](https://docs.mesosphere.com/service-docs/dse/) (in partnership with DataStax).
