### ISSUE TITLE
cassandra-mesos installed question

### ISSUE THREAD

**Issue by daikon12** [mesosphere/cassandra-mesos-deprecated#174]
Hi ! you are doing a great thing . I wonder the project of  cassandra-mesos-deprecated orhttps://github.com/mesosphere/dcos-cassandra-service can be installed and run on ubuntu14.04.I did it a long time ago , but  It is not work.

**Comment by triclambert** [comment]
This project is deprecated.  It will be archived on December 1, 2017.  Instead, please check out [Apache Cassandra for DC/OS](https://docs.mesosphere.com/service-docs/cassandra/).
